-- 00_provision.sql
-- Provision shared infrastructure for Q1 (and Q2) experiments
-- Account: <YOUR_ACCOUNT>
-- Run this FIRST before any other scripts

USE ROLE ACCOUNTADMIN;

-- Create dedicated warehouse
CREATE WAREHOUSE IF NOT EXISTS LAB_WH
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Create database
CREATE DATABASE IF NOT EXISTS CORTEX_AGENT_LAB;

-- Create schemas
CREATE SCHEMA IF NOT EXISTS CORTEX_AGENT_LAB.RAW;
CREATE SCHEMA IF NOT EXISTS CORTEX_AGENT_LAB.SEMANTIC;
CREATE SCHEMA IF NOT EXISTS CORTEX_AGENT_LAB.AGENTS;
CREATE SCHEMA IF NOT EXISTS CORTEX_AGENT_LAB.EVAL;

-- Enable cross-region inference (required for AI evaluation)
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

-- Set context
USE WAREHOUSE LAB_WH;
USE DATABASE CORTEX_AGENT_LAB;
