-- 00_provision.sql
-- Provision shared infrastructure (same as q1/q2)
-- Account: <YOUR_ACCOUNT>
-- Run this FIRST if not already provisioned by q1 or q2

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS LAB_WH
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS CORTEX_AGENT_LAB;

CREATE SCHEMA IF NOT EXISTS CORTEX_AGENT_LAB.RAW;
CREATE SCHEMA IF NOT EXISTS CORTEX_AGENT_LAB.SEMANTIC;
CREATE SCHEMA IF NOT EXISTS CORTEX_AGENT_LAB.AGENTS;
CREATE SCHEMA IF NOT EXISTS CORTEX_AGENT_LAB.EVAL;

ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

USE WAREHOUSE LAB_WH;
USE DATABASE CORTEX_AGENT_LAB;
